Fix #2764: False-negative when re-assigning variable
pmd/pmd pull request #2811
Opened 2020-10-01 11:34 UTC by andipabst

## Describe the PR

This PR fixes a false-negative when re-assigning a variable without closing it before.

## Related issues

- Fixes #2764 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

2020-10-01 11:51 UTC, pmd-test commented
<!--
  0 Errors
  1 Warning: Running pmdtester failed, this...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Running pmdtester failed, this message is mainly used to remind the maintainers of PMD.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-03 08:08 UTC, adangel approved these changes
Thanks, looks good!

I've retriggered the travis build to get the pmd-regression-tester results. They should arrive soon at https://github.com/pmd/pmd/pull/2811/#issuecomment-702081414 ...

2020-10-03 08:44 UTC, adangel requested changes
@andipabst 
Now that the regression tester ran, there are some problems, see https://chunk.io/pmd/29b0228064074bb390f40398e6069462/diff/spring-framework/index.html

* There are two NPEs:
```
java.lang.NullPointerException
 	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isAssignmentForVariable(CloseResourceRule.java:733)
 	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isReassignedBeforeBeingClosed(CloseResourceRule.java:690)
 	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.checkForResources(CloseResourceRule.java:172)
 	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.visit(CloseResourceRule.java:156)
```

and 

```
java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isAssignmentForVariable(CloseResourceRule.java:735)
	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isReassignedBeforeBeingClosed(CloseResourceRule.java:690)
	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.checkForResources(CloseResourceRule.java:172)
	at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.visit(CloseResourceRule.java:156)
```

* This might explain the false negatives in [FastByteArrayOutputStreamTests.java](https://chunk.io/pmd/29b0228064074bb390f40398e6069462/diff/spring-framework/index.html#A3)

* We seem to report now the initial assignment of the local var wrongly as a reassignment, e.g. https://chunk.io/pmd/29b0228064074bb390f40398e6069462/diff/spring-framework/index.html#A1

Could you please have another look? Thanks!

2020-10-10 09:02 UTC, andipabst commented
@adangel Thanks for showing me this. I added a check for null, but I am not sure if this fixes the regression, since I can not reproduce it in a unit test. Can you please tell me how I can run the regression test locally for myself?

2020-10-10 15:20 UTC, adangel commented
@andipabst The regression tester runs on every pull request. If you want to run it locally, have a look at https://github.com/pmd/pmd-regression-tester/blob/master/README.rdoc

To run it like in the PR, you could execute the following (in the PMD source directory, on your PR-branch):

```
bundle install
bundle exec pmdtester --local-git-repo ./ --base-branch master --patch-branch HEAD --mode online --auto-gen-config
```

After a while, you should have a diff report under `target/diff/index.html`.

But I don't think, running the tool locally is needed.


Looking at the new report generated by travis (https://chunk.io/pmd/26b5c9e13f1348e7a69413236d1f8ac5/diff/index.html), there are still some null pointers in the following files:
* https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/XmlBeanDefinitionReader.java
* https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-core/src/test/java/org/springframework/core/convert/support/StreamConverterTests.java
* https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-core/src/test/java/org/springframework/util/FastByteArrayOutputStreamTests.java
* https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-jdbc/src/main/java/org/springframework/jdbc/datasource/LazyConnectionDataSourceProxy.java
* https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-jdbc/src/main/java/org/springframework/jdbc/datasource/TransactionAwareDataSourceProxy.java

I'd suggest starting with one file. Put it simply as is into a new test case in closeresource.xml . That way, you should easily be able to reproduce the NPE. Then try to minimize the code sample to reproduce it, e.g. by removing one method after another. The NPE occurs while visiting a method, so find the method that is problematic.

2020-10-14 16:21 UTC, andipabst commented
@adangel Thank you, I did not notice that the top comment of the pmd-test bot was updated with the new result, my bad!

I had missed another null check, but could find it, now the regression test is producing no more errors. I also changed the location of the violation. Now the error gets flagged on the reassignment instead of the initial declaration.

2020-10-17 09:09 UTC, adangel approved these changes
Thanks, looks good!

2020-10-22 07:58 UTC, merged