[javascript] NPE while creating rule violation when specifying explicit line numbers
pmd/pmd pull request #3516
Opened 2021-09-21 17:47 UTC by kevingnet

## Describe the PR

AbstractEcmascriptRule has a function that takes begin and end lines as parameters. However when using, it produces a null pointer exception. This solution adds the call to the constructor for ParametricRuleViolation in which it was added support for those two line parameters. The new constructor calls the default constructor and then sets the line parameters. 

## Related issues

- Fixes #

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

2021-09-24 09:06 UTC, adangel requested changes
Thanks for the PR!

Please use the existing method [setLines(int, int)](https://github.com/pmd/pmd/blob/8a6bb312e197b9f05c8be2a3bbd4b57f33c4bcf8/pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ParametricRuleViolation.java#L186) instead of creating a new constructor.
You can call this method in EcmascriptRuleViolationFactory before returning the new rule violation.

2021-09-25 07:58 UTC, adangel commented
@kevingnet I've fixed this myself, so that this fix can be part of the release today...

2021-09-25 08:08 UTC, pmd-test commented
<!--
  0 Errors
  0 Warnings
  1 Message: No java rules are changed!
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-25 08:17 UTC, merged

2021-09-25 09:03 UTC, adangel commented
@all-contributors please add @kevingnet for code