[java] Modify the rule to meet the missing case #3603
pmd/pmd pull request #3938
Opened 2022-04-24 16:37 UTC by VoidxHoshi

## Describe the PR

This PR fixes the SimplifiedTernary rule for 'condition ? true : false' case encountered in issue 3603. This parse error has been fixed by changing the grammar in design.xml file.

## Related issues

- Fixes https://github.com/pmd/pmd/issues/3603

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

2022-04-24 18:17 UTC, oowekyala requested changes
Hi and thanks for the contribution!

This is missing a test case, although you added an example.

Please add a test case in the following file:

https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifiedTernary.xml

2022-04-24 18:17 UTC, oowekyala commented on pmd-java/src/main/resources/category/java/design.xml
> +or `condition ? literalBoolean1 : literalBoolean2`.
TBH this last one is a special case of the former two. We don't need to list it.

2022-04-24 18:17 UTC, oowekyala commented on pmd-java/src/main/resources/category/java/design.xml
> +`!condition` when the literalBoolean1 is false and the literalBoolean2 is true
I think it hard to read that the expressions are not next to each other

```suggestion
These expressions can be simplified as follows:
* `condition ? true : expr` simplifies to `condition || expr`
* `condition ? false : expr` simplifies to `!condition && expr`
* `condition ? expr : true` simplifies to `!condition || expr`
* `condition ? expr : false` simplifies to `condition && expr`
```

I don't think we need to also mention that if `expr` is `false` then `condition && expr` further simplifies to `false`, I think it's pretty easy to see.

2022-04-24 18:47 UTC, VoidxHoshi commented
well, I am confused about the code below in https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifiedTernary.xml

```xml
    <test-code>
        <description>condition ? true : false</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public boolean test() {
        return condition ? true : false; // Existing rule
    }
}
        ]]></code>
    </test-code>
```

Is it a false-positive rather than false-negative?
The `expected-problems` is 0

2022-04-24 19:09 UTC, oowekyala commented
You can update the test case to expect 1 violation, I think it was wrong. That has already been done in the dev branch for PMD 7, so it's not unexpected (PMD 7 rule: https://github.com/pmd/pmd/blob/pmd/7.0.x/pmd-java/src/main/resources/category/java/design.xml#L1150)

2022-04-24 20:04 UTC, VoidxHoshi commented
I am not familiar with XPath, but I run the test with the dev branch for PMD 7.
Then the test failed.
😢

2022-04-24 20:52 UTC, adangel commented on pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SimplifiedTernary.xml
> -        return condition ? true : false; // Existing rule
> // Existing rule

I wonder, whether we have another rule that would pick up this return statement...

But overall I think you change makes sense - this test case was wrong before. It should flag this return statement

2022-04-24 21:02 UTC, adangel commented
> I am not familiar with XPath, but I run the test with the dev branch for PMD 7. Then the test failed. And the test with your simplified XPath also failed. cry

There are other test cases that fail now:

```
  Error:    Run 3: SimplifiedTernaryTest>RuleTst.runTest:158 "condition ? foo : true" resulted in wrong number of failures, expected:<1> but was:<0>
  Error:    Run 4: SimplifiedTernaryTest>RuleTst.runTest:158 "condition ? foo : false" resulted in wrong number of failures, expected:<1> but was:<0>
  Error:    Run 7: SimplifiedTernaryTest>RuleTst.runTest:158 "#232 False positive with ternary operator using nullables" resulted in wrong number of failures, expected:<0> but was:<1>
```

It seems, we now don't detect anymore the first two cases ("condition ? foo: true" and "condition ? foo: false") and we reintroduced a false positive....

2022-04-26 11:07 UTC, oowekyala commented
> I am not familiar with XPath, but I run the test with the dev branch for PMD 7.

Rereading this, you should not be doing that ;) master and the pmd 7 branch build ASTs with a different form, so XPath expressions are not compatible. Since this PR targets master you should be testing your XPath queries on master

2022-04-26 20:02 UTC, VoidxHoshi commented
![image](https://user-images.githubusercontent.com/55886143/165382056-b1fed883-4460-42a3-801a-a825efeede6e.png)
Well, I think I have a basic grasp of XPath syntax now, can you give me a chance please? (These are my first few Pull Requests)
I think XPath should be changed to the following form (The screenshot shows that it can pass the test and it also passed the maven test in my PC).

```text
//ConditionalExpression[
((PrimaryExpression/*/Literal/BooleanLiteral) or (Expression/PrimaryExpression/*/Literal/BooleanLiteral))
and
not((PrimaryExpression/*/Literal/NullLiteral) or (Expression/PrimaryExpression/*/Literal/NullLiteral))
]
```

2022-04-26 20:58 UTC, VoidxHoshi commented
To address some special cases such as
```java
public class Foo {
    public boolean test() {
        return condition ? (true) : something();
    }
}
```
Maybe this form above is better
```text
//ConditionalExpression[
((//PrimaryExpression/*/Literal/BooleanLiteral) or (//Expression/PrimaryExpression/*/Literal/BooleanLiteral))
and
not((//PrimaryExpression/*/Literal/NullLiteral) or (//Expression/PrimaryExpression/*/Literal/NullLiteral))
]
```
And I don't konw why you use `*` rather than `PrimaryPrefix` (for compatibility?)

2022-04-26 21:10 UTC, VoidxHoshi commented
https://github.com/pmd/pmd/issues/2585 memtioned this problem too. 
I think it would be better to do this by modifying the SimplifiedTernary rule instead of modifying the SimplifyBooleanExpressions rule. It would also fix another similar problem https://github.com/pmd/pmd/issues/3604 at the same time.

2022-04-26 21:27 UTC, oowekyala commented
> https://github.com/pmd/pmd/issues/2585 memtioned this problem too.
I think it would be better to do this by modifying the SimplifiedTernary rule instead of modifying the SimplifyBooleanExpressions rule.

I think you're right, SimplifyBooleanExpressions should not overgrow its scope. This change is natural for SimplifiedTernary because it's a special case of the current definition of the rule anyway.

> It would also fix another similar problem https://github.com/pmd/pmd/issues/3604 at the same time.

Please don't take this on at the same time, open a followup PR after this one is merged. Also TBH I'm not sure this is even worth fixing, I'll add a comment on that issue.


> And I don't konw why the original code use \* rather than PrimaryPrefix (for compatibility?)

Because it's shorter. There's only one kind of node that may fit there, which is PrimaryPrefix, so it's redundant to mention it (although using `*` may make the query less efficient)

2022-04-26 21:28 UTC, oowekyala commented on pmd-java/src/main/resources/category/java/design.xml
> +]
Would be nicer if it was 
```suggestion
//ConditionalExpression
  [(Expression|.)/PrimaryExpression/*/Literal/BooleanLiteral]
  [not((Expression|.)/PrimaryExpression/*/Literal/NullLiteral)]
```

Both those expressions match `true ? e1 : e2`, which should be tested now.

2022-04-26 21:34 UTC, VoidxHoshi commented
What about the above case?
```java
public class Foo {
    public boolean test() {
        return condition ? (true) : something(); // the () break the rule
    }
}
```
I don't think it's worth opening a separate issue, do we need to fix it in this PR?

2022-04-26 21:43 UTC, oowekyala commented
TBH the parentheses are unnecessary, so UselessParentheses should report it. In PMD 7 `(true)` and `true` have the same AST so it works out of the box in SimplifiedTernary. I don't think it's worth fixing in PMD 6.

2022-04-26 21:46 UTC, VoidxHoshi commented
OK.
Thank you very much for your help and code review. I am new to PR and very unfamiliar with it, so I am very sorry if my stupidity bothers you.
😄

2022-04-26 21:55 UTC, oowekyala commented
Don't berate yourself, it's very brave to take on work in an unfamiliar project and propose changes upstream. Thanks for doing this&nbsp;:) Besides, please don't read annoyance in my comments. Writing in a laconic style just spares me some effort, it's nothing personal. I'll review again tomorrow.

2022-04-28 07:15 UTC, adangel approved these changes
Regression test results and unit tests look good. Thanks!

2022-04-28 11:39 UTC, oowekyala approved these changes
LGTM!

2022-04-28 13:18 UTC, merged