Add Gherkin support to CPD
pmd/pmd pull request #4017
Opened 2022-06-16 14:41 UTC by ASBrouwers

## Describe the PR

This adds support for the Gherkin language to CPD.

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

2022-06-23 13:13 UTC, adangel requested changes
Thanks for the PR!

Please have a look at my comments.
We have scheduled a new release (6.47.0) this Saturday already - so I'm not sure whether it will land in 6.47.0 or whether it has to wait for 6.48.0.

2022-06-23 13:13 UTC, adangel commented on pmd-gherkin/src/main/antlr4/net/sourceforge/pmd/lang/gherkin/antlr4/Gherkin.g4
> +FEATURE: 'Feature:';
We probably should mention somewhere, that only English is supported - non English variants of Gherkin can't be analyzed by pmd (see https://cucumber.io/docs/gherkin/reference/#spoken-languages)

2022-07-01 07:20 UTC, pmd-test commented
<!--
  0 Errors
  0 Warnings
  1 Message: Compared to master:<br />
This...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/1f9d679bea3f4148b2d10c2925529251/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-07-01 07:26 UTC, adangel approved these changes
Thanks, looks good!

2022-07-01 07:36 UTC, merged